# Generated by Django 6.0.6 on 2026-06-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_register_order_field_rename"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="date",
        ),
    ]
