# Generated by Django 6.0.6 on 2026-06-04 21:32

# Generated by Django 6.0.6 on 2026-06-04 21:32

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_backup_system'),
    ]

    operations = []
