# Generated by Django 5.2.6 on 2026-03-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_backup_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
