# Generated by Django 6.0.2 on 2026-02-09 16:22

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        # ...existing dependencies...
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=50, null=True, blank=True, db_column='role'),
        ),
    ]
