# Generated by Django 6.0.6 on 2026-06-04 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_remove_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                db_column="role",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.role",
            ),
        ),
    ]