# Generated by Django 6.0.6 on 2026-08-07 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_order_payment_difference"),
        ("api", "0042_order_payment_difference"),
    ]

    operations = []
